name: Frontent CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        
  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      
      - name: Test project
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist